### ISSUE TITLE
Stop on unknown key

### ISSUE THREAD

**Issue by mgudemann** [obcode/glabs#20]
I had put `startercod` in the .yml which resulted in empty repositories. Would
it make sense to stop with an error if an unknwon key ist encountered?

**Comment by obcode** [comment]
I have to check in the lib I use if that would be possible in an elegant way. Maybe I am going to include this in the `check` command.

Thanks!

**Comment by obcode** [comment]
It is not really feasible, at least not in an elegant way with the config handling library I am using (viper).

I recommend checking the colored config output before generating.

Is this good enough?

**Comment by mgudemann** [comment]
sure, that is fine
