### ISSUE TITLE
Missing config file is displayed w/o .yml extension in error message

### ISSUE THREAD

**Issue by max-fischer** [obcode/glabs#3]
If the config file is missing, one gets the following error message:
panic: fatal error config file: Config File "conffile" Not Found in <path>
As the name of the missing file is conffile.yml, it might be clearer to use the name with extension in the error message.

**Comment by obcode** [comment]
It is not that nice, since the part `Config File "conffile" Not Found in` comes from viper.

Error message is now:

```
panic: Config File "conffile" Not Found in "[...]": should be conffile.yml
```
