### ISSUE TITLE
Specifying a non-existing course name does not lead to an error message

### ISSUE THREAD

**Issue by wischhof** [obcode/glabs#7]
Just a minor issue - but since it took me a while to find out what was going wrong, still reported here: Currently, specifying a course that does not exist does not lead to an error message:

```
$ ./glabs.sh check somecoursethatdoesnotexist
6:31AM | DEBUG | D:/Hochschule/Lehrveranstaltungen/Netzwerke 1/Uebung_WS2021/gitlab/glabs/gitlab/gitlab.go:14 > connecting to gitlab server gitlab.host=https://gitlab.lrz.de/
 > checking usernames config of somecoursethatdoesnotexist
 >> checking students
 >> checking students in groups
 >>> checking duplicates in groups
```

Instead, terminating with an error message complaining that "somecoursethatdoesnotexist" does not exist, would be helpful. (Thought that I had a problem in my groups listing, instead I had a typo in the group name... ;-) )

**Comment by obcode** [comment]
Thanks for this report.
